# Mapeamento de Marca para Segmento (baseado na análise anterior)
BRAND_SEGMENT_MAP = {
    "Apple": "Tecnologia",
    "Samsung":"Tecnologia",
    "Apple": "Smartphones",
    "Samsung":"Smartphones",
    "Milka": "Alimentos",
    "DISNEY - HYPERION BOOKS": "Editorial",
    "AUDIBLE": "Editorial",
    "AUDIBLE FRONTIERS": "Editorial",
    "AUDIBLE STUDIOS": "Editorial",
    "BBC AUDIOBOOKS": "Editorial",
    "BLACKSTONE AUDIO": "Editorial",
    "BRILLIANCE AUDIO": "Editorial",
    "DREAMSCAPE MEDIA LLC": "Editorial",
    "HACHETTE AUDIO": "Editorial",
    "HIGHBRIDGE": "Editorial",
    "LISTENING LIBRARY (AUDIO)": "Editorial",
    "MACMILLAN AUDIO": "Editorial",
    "RANDOM HOUSE AUDIO": "Editorial",
    "SILHOUETTE AUDIO": "Editorial",
    "SIMON & SCHUSTER AUDIO": "Editorial",
    "SIMON SCHUSTER AUDIO/NIGHTINGALE - CONAN": "Editorial",
    "TIME WARNER AUDIOBOOKS": "Editorial",
    "AI PRESS": "Editorial",
    "ALADDIN": "Editorial",
    "AMAZON DIGITAL SERVICES INC": "Tecnologia/Editorial",
    "ATHENEUM BOOKS FOR YOUNG READERS": "Editorial",
    "AUTHORHOUSE": "Editorial",
    "BHD BOOKS": "Editorial",
    "BROADWAY BOOKS": "Editorial",
    "BRONWYN EDITIONS": "Editorial",
    "CORVUS": "Editorial",
    "CREATESPACE": "Editorial",
    "DARK HORIZONS PRESS": "Editorial",
    "DARUSSALAM PUBLISHERS": "Editorial",
    "DELACORTE BOOKS FOR YOUNG READERS": "Editorial",
    "DOUBLEDAY": "Editorial",
    "ENTANGLED PUBLISHING (INDULGENCE)": "Editorial",
    "EVERAFTER ROMANCE": "Editorial",
    "FIRE QUILL PUBLISHING": "Editorial",
    "HARMONY BOOKS": "Editorial",
    "HARPER PERENNIAL": "Editorial",
    "HIDDEN REALMS PUBLISHING": "Editorial",
    "HQN BOOKS": "Editorial",
    "IMMORTAL INK PUBLISHING": "Editorial",
    "JRI PUBLICATIONS": "Editorial",
    "JULIE MORGAN BOOKS": "Editorial",
    "KA LINDE": "Editorial",
    "KAREN BANEY": "Editorial",
    "KINDLE DIRECT PUBLISHING": "Editorial",
    "KNOPF BOOKS FOR YOUNG READERS": "Editorial",
    "KURO5HINORG": "Editorial",
    "LAMPLIGHTER PUBLISHING": "Editorial",
    "LAREE BAILEY PRESS": "Editorial",
    "MLR PRESS": "Editorial",
    "NLSA": "Editorial",
    "NPRB": "Editorial",
    "OPEN ROAD MEDIA INTEGRATED MEDIA": "Editorial",
    "ORBIT": "Editorial",
    "ORION": "Editorial",
    "PENGUIN": "Editorial",
    "PET TORRES": "Editorial",
    "PICADOR USA": "Editorial",
    "PINK CASHMERE PUBLISHING CO": "Editorial",
    "PODIOBOOKSCOM": "Editorial",
    "PULSE": "Editorial",
    "RANCHO PUBLISHING LLC": "Editorial",
    "ROBERT THIER": "Editorial",
    "ROLLING THUNDER ROMANCE": "Editorial",
    "ROSICRUCIAN FELLOWSHIP": "Editorial",
    "SAMHAIN PUBLISHING": "Editorial",
    "SC STEPHENS": "Editorial",
    "SEELEY JAMES": "Editorial",
    "SHERE": "Editorial",
    "SITA BENNETT": "Editorial",
    "SMALL BEER PRESS": "Editorial",
    "SMASHWORDS": "Editorial",
    "SMASHWORDS EDITION": "Editorial",
    "SPECTRUM LITERARY AGENCY": "Editorial",
    "SRISHTI PUBLISHERS AND DISTRIBUTORS": "Editorial",
    "STURGEON CREEK PUBLISHING": "Editorial",
    "TELL - TALE PUBLISHING GROUP LLC": "Editorial",
    "THE RUNAWAY PEN": "Editorial",
    "THE WRITER ' S COFFEE SHOP PUBLISHING HO": "Editorial",
    "TIMES SQUARE PUBLISHING": "Editorial",
    "TOR": "Editorial",
    "URBAN CHRISTIAN": "Editorial",
    "VIRTUE BOOK PUBLISHERS": "Editorial",
    "WATTPAD": "Editorial",
    "WE - LIT INC": "Editorial",
    "WESTMINSTER/JOHN KNOX PRESS (PHILADELPHI)": "Editorial",
    "YOUCANPRINT SELF - PUBLISHING": "Editorial",
    "Bartira": "Móveis",
    "Beringer": "Bebidas",
    "Bonne Maman": "Alimentos",
    "Brewdog": "Bebidas",
    "ChefPro": "Equipamentos",
    "Droste": "Alimentos",
    "Duckhorn": "Bebidas",
    "DutchCheeseMan": "Alimentos",
    "FeverTree": "Bebidas",
    "GLENLIVET": "Bebidas",
    "GuyLian": "Alimentos",
    "Hershey's": "Alimentos",
    "Hotel Chocolat": "Alimentos",
    "Leonidas": "Alimentos",
    "Little Debbie": "Alimentos",
    "MaisonFromage": "Alimentos",
    "Marios": "Alimentos",
    "PetLover": "Produtos",
    "PureBake": "Alimentos",
    "PureTaste": "Alimentos",
    "Purebake": "Alimentos",
    "SmartHouse": "Tecnologia",
    "Multi Brand": "Indefinido"
}
BRANDS = sorted(list(set(BRAND_SEGMENT_MAP.keys())))
BRANDS.insert(0, "Tudo")  # Adiciona opção "Tudo"

SEGMENTS = sorted(list(set(BRAND_SEGMENT_MAP.values())))
SEGMENTS.insert(0, "Tudo") # Adiciona a opção "Tudo" no início
